CREATE TABLE PRODUCTS(
ID INT PRIMARY KEY IDENTITY NOT NULL,
NAME VARCHAR(38),
PRICE MONEY);

CREATE TABLE CUSTOMERS(
ID INT PRIMARY KEY IDENTITY NOT NULL,
Firstname VARCHAR(38) NOT NULL,
Lastname VARCHAR(38) NOT NULL,
CardNumber CHAR(38) NOT NULL
);

CREATE TABLE ORDERS(
ID INT PRIMARY KEY IDENTITY NOT NULL,
PRODUCTID INT NOT NULL
	CONSTRAINT FK_PRODUCT_ID
	REFERENCES PRODUCTS (ID),
CUSTOMERID INT NOT NULL
	CONSTRAINT FR_CUSTOMER_ID
	REFERENCES CUSTOMERS (ID)
	);

INSERT INTO CUSTOMERS ( Firstname, Lastname, CardNumber)
VALUES ( 'Tom', 'Tibidoe', 80756201005803400471)

INSERT INTO CUSTOMERS ( Firstname, Lastname, CardNumber)
VALUES ( 'Juan', 'Frutos', 69756201005803400471)

INSERT INTO PRODUCTS ( Name, Price)
VALUES ( 'Samsung', 300)

INSERT INTO PRODUCTS (Name, Price)
VALUES ( 'Watch')
INSERT INTO PRODUCTS  ( Name, Price)
VALUES ( 'iPhone', 200)

INSERT INTO CUSTOMER (ID, Firstname, Lastname, CardNumber)
VALUES (1, 'Tina', 'Smith', 80756201005803400471)

--report all ordres by Tina Smith.
SELECT
FROM ORDERS INNER JOIN CUSTOMERS ON CUSTOMER_ID = CUSTOMERID
LEFT JOIN  
WHERE PRODUCTID = 1;


UPDATE PRODUCTS
SET PRICE = 250
WHERE Name ='iPhone';